apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: simple-service
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: simple-service
    weight: 100
  wildcardPolicy: None
